** {'keywords': {'batch_dim': 0,
                 'input': <tf.Tensor 'strided_slice_1:0' shape=(32, ?, 90) dtype=float32>,
                 'seq_dim': 1,
                 'seq_lengths': <tf.Tensor 'Minimum_1:0' shape=(32,) dtype=int32>},
    'name': None,
    'op_type_name': 'ReverseSequence',
    'self': <tensorflow.python.framework.op_def_library.OpDefLibrary object at 0x11a824cf8>}
** {'keywords': {'batch_dim': 0,
                 'input': <tf.Tensor 'strided_slice_1:0' shape=(32, ?, 90) dtype=float32>,
                 'seq_dim': 1,
                 'seq_lengths': <tf.Tensor 'Minimum_1:0' shape=(32,) dtype=int32>},
    'name': None,
    'op_type_name': 'ReverseSequence',
    'self': <tensorflow.python.framework.op_def_library.OpDefLibrary object at 0x11a824cf8>}
** {'keywords': {'batch_dim': 0,
                 'input': <tf.Tensor 'strided_slice_1:0' shape=(32, ?, 90) dtype=float32>,
                 'seq_dim': 1,
                 'seq_lengths': <tf.Tensor 'Minimum_1:0' shape=(32,) dtype=int32>},
    'name': None,
    'op_type_name': 'ReverseSequence',
    'self': <tensorflow.python.framework.op_def_library.OpDefLibrary object at 0x11a824cf8>}
** {'keywords': {'batch_dim': 0,
                 'input': <tf.Tensor 'strided_slice_1:0' shape=(32, ?, 90) dtype=float32>,
                 'seq_dim': 1,
                 'seq_lengths': <tf.Tensor 'Minimum_1:0' shape=(32,) dtype=int32>},
    'name': None,
    'op_type_name': 'ReverseSequence',
    'self': <tensorflow.python.framework.op_def_library.OpDefLibrary object at 0x11a824cf8>}
** {'keywords': {'batch_dim': 0,
                 'input': <tf.Tensor 'strided_slice_1:0' shape=(32, ?, 90) dtype=float32>,
                 'seq_dim': 1,
                 'seq_lengths': <tf.Tensor 'Minimum_1:0' shape=(32,) dtype=int32>},
    'name': None,
    'op_type_name': 'ReverseSequence',
    'self': <tensorflow.python.framework.op_def_library.OpDefLibrary object at 0x11a824cf8>}
** {'keywords': {'batch_dim': 0,
                 'input': <tf.Tensor 'strided_slice_1:0' shape=(32, ?, 90) dtype=float32>,
                 'seq_dim': 1,
                 'seq_lengths': <tf.Tensor 'Minimum_1:0' shape=(32,) dtype=int32>},
    'name': None,
    'op_type_name': 'ReverseSequence',
    'self': <tensorflow.python.framework.op_def_library.OpDefLibrary object at 0x11a824cf8>}
** {'keywords': {'batch_dim': 0,
                 'input': <tf.Tensor 'strided_slice_1:0' shape=(32, ?, 90) dtype=float32>,
                 'seq_dim': 1,
                 'seq_lengths': <tf.Tensor 'Minimum_1:0' shape=(32,) dtype=int32>},
    'name': None,
    'op_type_name': 'ReverseSequence',
    'self': <tensorflow.python.framework.op_def_library.OpDefLibrary object at 0x11a824cf8>}
** {'keywords': {'batch_dim': 0,
                 'input': <tf.Tensor 'strided_slice_1:0' shape=(32, ?, 90) dtype=float32>,
                 'seq_dim': 1,
                 'seq_lengths': <tf.Tensor 'Minimum_1:0' shape=(32,) dtype=int32>},
    'name': None,
    'op_type_name': 'ReverseSequence',
    'self': <tensorflow.python.framework.op_def_library.OpDefLibrary object at 0x11a824cf8>}
** {'keywords': {'batch_dim': 0,
                 'input': <tf.Tensor 'strided_slice_1:0' shape=(32, ?, 90) dtype=float32>,
                 'seq_dim': 1,
                 'seq_lengths': <tf.Tensor 'Minimum_1:0' shape=(32,) dtype=int32>},
    'name': 'ReverseSequence',
    'op_type_name': 'ReverseSequence',
    'self': <tensorflow.python.framework.op_def_library.OpDefLibrary object at 0x11a824cf8>}
** {'keywords': {'batch_dim': 0,
                 'input': <tf.Tensor 'strided_slice_1:0' shape=(32, ?, 90) dtype=float32>,
                 'seq_dim': 1,
                 'seq_lengths': <tf.Tensor 'Minimum_1:0' shape=(32,) dtype=int32>},
    'name': 'ReverseSequence',
    'op_type_name': 'ReverseSequence',
    'self': <tensorflow.python.framework.op_def_library.OpDefLibrary object at 0x11a824cf8>}
** {'keywords': {'batch_dim': 0,
                 'input': <tf.Tensor 'strided_slice_1:0' shape=(32, ?, 90) dtype=float32>,
                 'seq_dim': 1,
                 'seq_lengths': <tf.Tensor 'Minimum_1:0' shape=(32,) dtype=int32>},
    'name': 'ReverseSequence',
    'op_type_name': 'ReverseSequence',
    'self': <tensorflow.python.framework.op_def_library.OpDefLibrary object at 0x11a824cf8>}
** {'keywords': {'batch_dim': 0,
                 'input': <tf.Tensor 'strided_slice_1:0' shape=(32, ?, 90) dtype=float32>,
                 'seq_dim': 1,
                 'seq_lengths': <tf.Tensor 'Minimum_1:0' shape=(32,) dtype=int32>},
    'name': 'ReverseSequence',
    'op_type_name': 'ReverseSequence',
    'self': <tensorflow.python.framework.op_def_library.OpDefLibrary object at 0x11a824cf8>}
** {'keywords': {'batch_dim': 0,
                 'input': <tf.Tensor 'strided_slice_1:0' shape=(32, ?, 90) dtype=float32>,
                 'seq_dim': 1,
                 'seq_lengths': <tf.Tensor 'Minimum_1:0' shape=(32,) dtype=int32>},
    'name': 'ReverseSequence',
    'op_type_name': 'ReverseSequence',
    'self': <tensorflow.python.framework.op_def_library.OpDefLibrary object at 0x11a824cf8>}
** {'keywords': {'batch_dim': 0,
                 'input': <tf.Tensor 'strided_slice_1:0' shape=(32, ?, 90) dtype=float32>,
                 'seq_dim': 1,
                 'seq_lengths': <tf.Tensor 'Minimum_1:0' shape=(32,) dtype=int32>},
    'name': 'ReverseSequence',
    'op_type_name': 'ReverseSequence',
    'self': <tensorflow.python.framework.op_def_library.OpDefLibrary object at 0x11a824cf8>}
** {'keywords': {'batch_dim': 0,
                 'input': <tf.Tensor 'strided_slice_1:0' shape=(32, ?, 90) dtype=float32>,
                 'seq_dim': 1,
                 'seq_lengths': <tf.Tensor 'Minimum_1:0' shape=(32,) dtype=int32>},
    'name': 'ReverseSequence',
    'op_type_name': 'ReverseSequence',
    'self': <tensorflow.python.framework.op_def_library.OpDefLibrary object at 0x11a824cf8>}
** {'keywords': {'batch_dim': 0,
                 'input': <tf.Tensor 'strided_slice_1:0' shape=(32, ?, 90) dtype=float32>,
                 'seq_dim': 1,
                 'seq_lengths': <tf.Tensor 'Minimum_1:0' shape=(32,) dtype=int32>},
    'name': 'ReverseSequence',
    'op_type_name': 'ReverseSequence',
    'self': <tensorflow.python.framework.op_def_library.OpDefLibrary object at 0x11a824cf8>}
** {'keywords': {'batch_dim': 0,
                 'input': <tf.Tensor 'strided_slice_1:0' shape=(32, ?, 90) dtype=float32>,
                 'seq_dim': 1,
                 'seq_lengths': <tf.Tensor 'Minimum_1:0' shape=(32,) dtype=int32>},
    'name': 'ReverseSequence',
    'op_type_name': 'ReverseSequence',
    'self': <tensorflow.python.framework.op_def_library.OpDefLibrary object at 0x11a824cf8>}
** {'keywords': {'batch_dim': 0,
                 'input': <tf.Tensor 'strided_slice_1:0' shape=(32, ?, 90) dtype=float32>,
                 'seq_dim': 1,
                 'seq_lengths': <tf.Tensor 'Minimum_1:0' shape=(32,) dtype=int32>},
    'name': 'ReverseSequence',
    'op_type_name': 'ReverseSequence',
    'self': <tensorflow.python.framework.op_def_library.OpDefLibrary object at 0x11a824cf8>}
** {'keywords': {'batch_dim': 0,
                 'input': <tf.Tensor 'strided_slice_1:0' shape=(32, ?, 90) dtype=float32>,
                 'seq_dim': 1,
                 'seq_lengths': <tf.Tensor 'Minimum_1:0' shape=(32,) dtype=int32>},
    'name': 'ReverseSequence',
    'op_type_name': 'ReverseSequence',
    'self': <tensorflow.python.framework.op_def_library.OpDefLibrary object at 0x11a824cf8>}
** {'keywords': {'batch_dim': 0,
                 'input': <tf.Tensor 'strided_slice_1:0' shape=(32, ?, 90) dtype=float32>,
                 'seq_dim': 1,
                 'seq_lengths': <tf.Tensor 'Minimum_1:0' shape=(32,) dtype=int32>},
    'name': 'ReverseSequence',
    'op_type_name': 'ReverseSequence',
    'self': <tensorflow.python.framework.op_def_library.OpDefLibrary object at 0x11a824cf8>}
** {'key': 'T',
    'keywords': {'batch_dim': 0,
                 'input': <tf.Tensor 'strided_slice_1:0' shape=(32, ?, 90) dtype=float32>,
                 'seq_dim': 1,
                 'seq_lengths': <tf.Tensor 'Minimum_1:0' shape=(32,) dtype=int32>},
    'name': 'ReverseSequence',
    'op_type_name': 'ReverseSequence',
    'self': <tensorflow.python.framework.op_def_library.OpDefLibrary object at 0x11a824cf8>}
** {'key': 'T',
    'keywords': {'batch_dim': 0,
                 'input': <tf.Tensor 'strided_slice_1:0' shape=(32, ?, 90) dtype=float32>,
                 'seq_dim': 1,
                 'seq_lengths': <tf.Tensor 'Minimum_1:0' shape=(32,) dtype=int32>},
    'name': 'ReverseSequence',
    'op_type_name': 'ReverseSequence',
    'self': <tensorflow.python.framework.op_def_library.OpDefLibrary object at 0x11a824cf8>}
** {'key': 'T',
    'keywords': {'batch_dim': 0,
                 'input': <tf.Tensor 'strided_slice_1:0' shape=(32, ?, 90) dtype=float32>,
                 'seq_dim': 1,
                 'seq_lengths': <tf.Tensor 'Minimum_1:0' shape=(32,) dtype=int32>},
    'name': 'ReverseSequence',
    'op_type_name': 'ReverseSequence',
    'self': <tensorflow.python.framework.op_def_library.OpDefLibrary object at 0x11a824cf8>}
** {'key': 'T',
    'keywords': {'batch_dim': 0,
                 'input': <tf.Tensor 'strided_slice_1:0' shape=(32, ?, 90) dtype=float32>,
                 'seq_dim': 1,
                 'seq_lengths': <tf.Tensor 'Minimum_1:0' shape=(32,) dtype=int32>},
    'name': 'ReverseSequence',
    'op_type_name': 'ReverseSequence',
    'self': <tensorflow.python.framework.op_def_library.OpDefLibrary object at 0x11a824cf8>}
** {'key': 'Tlen',
    'keywords': {'batch_dim': 0,
                 'input': <tf.Tensor 'strided_slice_1:0' shape=(32, ?, 90) dtype=float32>,
                 'seq_dim': 1,
                 'seq_lengths': <tf.Tensor 'Minimum_1:0' shape=(32,) dtype=int32>},
    'name': 'ReverseSequence',
    'op_type_name': 'ReverseSequence',
    'self': <tensorflow.python.framework.op_def_library.OpDefLibrary object at 0x11a824cf8>}
** {'key': 'Tlen',
    'keywords': {'batch_dim': 0,
                 'input': <tf.Tensor 'strided_slice_1:0' shape=(32, ?, 90) dtype=float32>,
                 'seq_dim': 1,
                 'seq_lengths': <tf.Tensor 'Minimum_1:0' shape=(32,) dtype=int32>},
    'name': 'ReverseSequence',
    'op_type_name': 'ReverseSequence',
    'self': <tensorflow.python.framework.op_def_library.OpDefLibrary object at 0x11a824cf8>}
** {'key': 'Tlen',
    'keywords': {'batch_dim': 0,
                 'input': <tf.Tensor 'strided_slice_1:0' shape=(32, ?, 90) dtype=float32>,
                 'seq_dim': 1,
                 'seq_lengths': <tf.Tensor 'Minimum_1:0' shape=(32,) dtype=int32>},
    'name': 'ReverseSequence',
    'op_type_name': 'ReverseSequence',
    'self': <tensorflow.python.framework.op_def_library.OpDefLibrary object at 0x11a824cf8>}
** {'key': 'Tlen',
    'keywords': {'batch_dim': 0,
                 'input': <tf.Tensor 'strided_slice_1:0' shape=(32, ?, 90) dtype=float32>,
                 'seq_dim': 1,
                 'seq_lengths': <tf.Tensor 'Minimum_1:0' shape=(32,) dtype=int32>},
    'name': 'ReverseSequence',
    'op_type_name': 'ReverseSequence',
    'self': <tensorflow.python.framework.op_def_library.OpDefLibrary object at 0x11a824cf8>}
** {'key': 'Tlen',
    'keywords': {'batch_dim': 0,
                 'input': <tf.Tensor 'strided_slice_1:0' shape=(32, ?, 90) dtype=float32>,
                 'seq_dim': 1,
                 'seq_lengths': <tf.Tensor 'Minimum_1:0' shape=(32,) dtype=int32>},
    'name': 'ReverseSequence',
    'op_type_name': 'ReverseSequence',
    'self': <tensorflow.python.framework.op_def_library.OpDefLibrary object at 0x11a824cf8>}
** {'key': 'Tlen',
    'keywords': {'batch_dim': 0,
                 'input': <tf.Tensor 'strided_slice_1:0' shape=(32, ?, 90) dtype=float32>,
                 'seq_dim': 1,
                 'seq_lengths': <tf.Tensor 'Minimum_1:0' shape=(32,) dtype=int32>},
    'name': 'ReverseSequence',
    'op_type_name': 'ReverseSequence',
    'self': <tensorflow.python.framework.op_def_library.OpDefLibrary object at 0x11a824cf8>}
** {'inputs': [],
    'key': 'Tlen',
    'keywords': {'batch_dim': 0,
                 'input': <tf.Tensor 'strided_slice_1:0' shape=(32, ?, 90) dtype=float32>,
                 'seq_dim': 1,
                 'seq_lengths': <tf.Tensor 'Minimum_1:0' shape=(32,) dtype=int32>},
    'name': 'ReverseSequence',
    'op_type_name': 'ReverseSequence',
    'self': <tensorflow.python.framework.op_def_library.OpDefLibrary object at 0x11a824cf8>}
** {'input_types': [],
    'inputs': [],
    'key': 'Tlen',
    'keywords': {'batch_dim': 0,
                 'input': <tf.Tensor 'strided_slice_1:0' shape=(32, ?, 90) dtype=float32>,
                 'seq_dim': 1,
                 'seq_lengths': <tf.Tensor 'Minimum_1:0' shape=(32,) dtype=int32>},
    'name': 'ReverseSequence',
    'op_type_name': 'ReverseSequence',
    'self': <tensorflow.python.framework.op_def_library.OpDefLibrary object at 0x11a824cf8>}
** {'input_types': [],
    'inputs': [],
    'key': 'Tlen',
    'keywords': {'batch_dim': 0,
                 'input': <tf.Tensor 'strided_slice_1:0' shape=(32, ?, 90) dtype=float32>,
                 'seq_dim': 1,
                 'seq_lengths': <tf.Tensor 'Minimum_1:0' shape=(32,) dtype=int32>},
    'name': 'ReverseSequence',
    'op_type_name': 'ReverseSequence',
    'scope': 'encoder/cell_0/bidirectional_rnn/bw/ReverseSequence/',
    'self': <tensorflow.python.framework.op_def_library.OpDefLibrary object at 0x11a824cf8>}
** {'inferred_from': {},
    'input_types': [],
    'inputs': [],
    'key': 'Tlen',
    'keywords': {'batch_dim': 0,
                 'input': <tf.Tensor 'strided_slice_1:0' shape=(32, ?, 90) dtype=float32>,
                 'seq_dim': 1,
                 'seq_lengths': <tf.Tensor 'Minimum_1:0' shape=(32,) dtype=int32>},
    'name': 'ReverseSequence',
    'op_type_name': 'ReverseSequence',
    'scope': 'encoder/cell_0/bidirectional_rnn/bw/ReverseSequence/',
    'self': <tensorflow.python.framework.op_def_library.OpDefLibrary object at 0x11a824cf8>}
** {'inferred_from': {},
    'input_types': [],
    'inputs': [],
    'key': 'Tlen',
    'keywords': {'batch_dim': 0,
                 'input': <tf.Tensor 'strided_slice_1:0' shape=(32, ?, 90) dtype=float32>,
                 'seq_dim': 1,
                 'seq_lengths': <tf.Tensor 'Minimum_1:0' shape=(32,) dtype=int32>},
    'name': 'ReverseSequence',
    'op_type_name': 'ReverseSequence',
    'scope': 'encoder/cell_0/bidirectional_rnn/bw/ReverseSequence/',
    'self': <tensorflow.python.framework.op_def_library.OpDefLibrary object at 0x11a824cf8>}
** {'inferred_from': {},
    'input_types': [],
    'inputs': [],
    'key': 'Tlen',
    'keywords': {'batch_dim': 0,
                 'input': <tf.Tensor 'strided_slice_1:0' shape=(32, ?, 90) dtype=float32>,
                 'seq_dim': 1,
                 'seq_lengths': <tf.Tensor 'Minimum_1:0' shape=(32,) dtype=int32>},
    'name': 'ReverseSequence',
    'op_type_name': 'ReverseSequence',
    'scope': 'encoder/cell_0/bidirectional_rnn/bw/ReverseSequence/',
    'self': <tensorflow.python.framework.op_def_library.OpDefLibrary object at 0x11a824cf8>}
** {'inferred_from': {},
    'input_types': [],
    'inputs': [],
    'key': 'Tlen',
    'keywords': {'batch_dim': 0,
                 'input': <tf.Tensor 'strided_slice_1:0' shape=(32, ?, 90) dtype=float32>,
                 'seq_dim': 1,
                 'seq_lengths': <tf.Tensor 'Minimum_1:0' shape=(32,) dtype=int32>},
    'name': 'ReverseSequence',
    'op_type_name': 'ReverseSequence',
    'scope': 'encoder/cell_0/bidirectional_rnn/bw/ReverseSequence/',
    'self': <tensorflow.python.framework.op_def_library.OpDefLibrary object at 0x11a824cf8>}
** {'_v1': <tf.Tensor 'strided_slice_1:0' shape=(32, ?, 90) dtype=float32>,
    'inferred_from': {},
    'input_types': [],
    'inputs': [],
    'key': 'Tlen',
    'keywords': {'batch_dim': 0,
                 'seq_dim': 1,
                 'seq_lengths': <tf.Tensor 'Minimum_1:0' shape=(32,) dtype=int32>},
    'name': 'ReverseSequence',
    'op_type_name': 'ReverseSequence',
    'scope': 'encoder/cell_0/bidirectional_rnn/bw/ReverseSequence/',
    'self': <tensorflow.python.framework.op_def_library.OpDefLibrary object at 0x11a824cf8>,
    'values': <tf.Tensor 'strided_slice_1:0' shape=(32, ?, 90) dtype=float32>}
** {'_v1': <tf.Tensor 'strided_slice_1:0' shape=(32, ?, 90) dtype=float32>,
    'inferred_from': {},
    'input_types': [],
    'inputs': [],
    'key': 'Tlen',
    'keywords': {'batch_dim': 0,
                 'seq_dim': 1,
                 'seq_lengths': <tf.Tensor 'Minimum_1:0' shape=(32,) dtype=int32>},
    'name': 'ReverseSequence',
    'op_type_name': 'ReverseSequence',
    'scope': 'encoder/cell_0/bidirectional_rnn/bw/ReverseSequence/',
    'self': <tensorflow.python.framework.op_def_library.OpDefLibrary object at 0x11a824cf8>,
    'values': <tf.Tensor 'strided_slice_1:0' shape=(32, ?, 90) dtype=float32>}
** {'_v1': <tf.Tensor 'strided_slice_1:0' shape=(32, ?, 90) dtype=float32>,
    'dtype': None,
    'inferred_from': {},
    'input_types': [],
    'inputs': [],
    'key': 'Tlen',
    'keywords': {'batch_dim': 0,
                 'seq_dim': 1,
                 'seq_lengths': <tf.Tensor 'Minimum_1:0' shape=(32,) dtype=int32>},
    'name': 'ReverseSequence',
    'op_type_name': 'ReverseSequence',
    'scope': 'encoder/cell_0/bidirectional_rnn/bw/ReverseSequence/',
    'self': <tensorflow.python.framework.op_def_library.OpDefLibrary object at 0x11a824cf8>,
    'values': <tf.Tensor 'strided_slice_1:0' shape=(32, ?, 90) dtype=float32>}
** {'_v1': <tf.Tensor 'strided_slice_1:0' shape=(32, ?, 90) dtype=float32>,
    'default_dtype': None,
    'dtype': None,
    'inferred_from': {},
    'input_types': [],
    'inputs': [],
    'key': 'Tlen',
    'keywords': {'batch_dim': 0,
                 'seq_dim': 1,
                 'seq_lengths': <tf.Tensor 'Minimum_1:0' shape=(32,) dtype=int32>},
    'name': 'ReverseSequence',
    'op_type_name': 'ReverseSequence',
    'scope': 'encoder/cell_0/bidirectional_rnn/bw/ReverseSequence/',
    'self': <tensorflow.python.framework.op_def_library.OpDefLibrary object at 0x11a824cf8>,
    'values': <tf.Tensor 'strided_slice_1:0' shape=(32, ?, 90) dtype=float32>}
** {'_v1': <tf.Tensor 'strided_slice_1:0' shape=(32, ?, 90) dtype=float32>,
    'default_dtype': None,
    'dtype': None,
    'inferred_from': {},
    'input_types': [],
    'inputs': [],
    'key': 'Tlen',
    'keywords': {'batch_dim': 0,
                 'seq_dim': 1,
                 'seq_lengths': <tf.Tensor 'Minimum_1:0' shape=(32,) dtype=int32>},
    'name': 'ReverseSequence',
    'op_type_name': 'ReverseSequence',
    'scope': 'encoder/cell_0/bidirectional_rnn/bw/ReverseSequence/',
    'self': <tensorflow.python.framework.op_def_library.OpDefLibrary object at 0x11a824cf8>,
    'values': <tf.Tensor 'strided_slice_1:0' shape=(32, ?, 90) dtype=float32>}
** {'_v1': <tf.Tensor 'strided_slice_1:0' shape=(32, ?, 90) dtype=float32>,
    'default_dtype': None,
    'dtype': None,
    'inferred_from': {},
    'input_types': [],
    'inputs': [],
    'key': 'Tlen',
    'keywords': {'batch_dim': 0,
                 'seq_dim': 1,
                 'seq_lengths': <tf.Tensor 'Minimum_1:0' shape=(32,) dtype=int32>},
    'name': 'ReverseSequence',
    'op_type_name': 'ReverseSequence',
    'scope': 'encoder/cell_0/bidirectional_rnn/bw/ReverseSequence/',
    'self': <tensorflow.python.framework.op_def_library.OpDefLibrary object at 0x11a824cf8>,
    'values': <tf.Tensor 'strided_slice_1:0' shape=(32, ?, 90) dtype=float32>}
** {'_v1': <tf.Tensor 'strided_slice_1:0' shape=(32, ?, 90) dtype=float32>,
    'default_dtype': None,
    'dtype': None,
    'inferred_from': {},
    'input_types': [],
    'inputs': [],
    'key': 'Tlen',
    'keywords': {'batch_dim': 0,
                 'seq_dim': 1,
                 'seq_lengths': <tf.Tensor 'Minimum_1:0' shape=(32,) dtype=int32>},
    'name': 'ReverseSequence',
    'op_type_name': 'ReverseSequence',
    'scope': 'encoder/cell_0/bidirectional_rnn/bw/ReverseSequence/',
    'self': <tensorflow.python.framework.op_def_library.OpDefLibrary object at 0x11a824cf8>,
    'values': <tf.Tensor 'strided_slice_1:0' shape=(32, ?, 90) dtype=float32>}
** {'_v1': <tf.Tensor 'strided_slice_1:0' shape=(32, ?, 90) dtype=float32>,
    'default_dtype': None,
    'dtype': None,
    'inferred_from': {},
    'input_types': [],
    'inputs': [],
    'key': 'Tlen',
    'keywords': {'batch_dim': 0,
                 'seq_dim': 1,
                 'seq_lengths': <tf.Tensor 'Minimum_1:0' shape=(32,) dtype=int32>},
    'name': 'ReverseSequence',
    'op_type_name': 'ReverseSequence',
    'scope': 'encoder/cell_0/bidirectional_rnn/bw/ReverseSequence/',
    'self': <tensorflow.python.framework.op_def_library.OpDefLibrary object at 0x11a824cf8>,
    'values': <tf.Tensor 'strided_slice_1:0' shape=(32, ?, 90) dtype=float32>}
** {'_v1': <tf.Tensor 'strided_slice_1:0' shape=(32, ?, 90) dtype=float32>,
    'default_dtype': None,
    'dtype': None,
    'inferred_from': {},
    'input_types': [],
    'inputs': [],
    'key': 'Tlen',
    'keywords': {'batch_dim': 0,
                 'seq_dim': 1,
                 'seq_lengths': <tf.Tensor 'Minimum_1:0' shape=(32,) dtype=int32>},
    'name': 'ReverseSequence',
    'op_type_name': 'ReverseSequence',
    'scope': 'encoder/cell_0/bidirectional_rnn/bw/ReverseSequence/',
    'self': <tensorflow.python.framework.op_def_library.OpDefLibrary object at 0x11a824cf8>,
    'values': <tf.Tensor 'strided_slice_1:0' shape=(32, ?, 90) dtype=float32>}
** {'_v1': <tf.Tensor 'strided_slice_1:0' shape=(32, ?, 90) dtype=float32>,
    'default_dtype': None,
    'dtype': None,
    'inferred_from': {},
    'input_types': [],
    'inputs': [],
    'key': 'Tlen',
    'keywords': {'batch_dim': 0,
                 'seq_dim': 1,
                 'seq_lengths': <tf.Tensor 'Minimum_1:0' shape=(32,) dtype=int32>},
    'name': 'ReverseSequence',
    'op_type_name': 'ReverseSequence',
    'scope': 'encoder/cell_0/bidirectional_rnn/bw/ReverseSequence/',
    'self': <tensorflow.python.framework.op_def_library.OpDefLibrary object at 0x11a824cf8>,
    'values': <tf.Tensor 'strided_slice_1:0' shape=(32, ?, 90) dtype=float32>}
** {'_v1': <tf.Tensor 'strided_slice_1:0' shape=(32, ?, 90) dtype=float32>,
    'default_dtype': None,
    'dtype': None,
    'inferred_from': {},
    'input_types': [],
    'inputs': [],
    'key': 'Tlen',
    'keywords': {'batch_dim': 0,
                 'seq_dim': 1,
                 'seq_lengths': <tf.Tensor 'Minimum_1:0' shape=(32,) dtype=int32>},
    'name': 'ReverseSequence',
    'op_type_name': 'ReverseSequence',
    'scope': 'encoder/cell_0/bidirectional_rnn/bw/ReverseSequence/',
    'self': <tensorflow.python.framework.op_def_library.OpDefLibrary object at 0x11a824cf8>,
    'values': <tf.Tensor 'strided_slice_1:0' shape=(32, ?, 90) dtype=float32>}
** {'_v1': <tf.Tensor 'strided_slice_1:0' shape=(32, ?, 90) dtype=float32>,
    'default_dtype': None,
    'dtype': None,
    'inferred_from': {},
    'input_types': [],
    'inputs': [],
    'key': 'Tlen',
    'keywords': {'batch_dim': 0,
                 'seq_dim': 1,
                 'seq_lengths': <tf.Tensor 'Minimum_1:0' shape=(32,) dtype=int32>},
    'name': 'ReverseSequence',
    'op_type_name': 'ReverseSequence',
    'scope': 'encoder/cell_0/bidirectional_rnn/bw/ReverseSequence/',
    'self': <tensorflow.python.framework.op_def_library.OpDefLibrary object at 0x11a824cf8>,
    'values': <tf.Tensor 'strided_slice_1:0' shape=(32, ?, 90) dtype=float32>}
** {'_v1': <tf.Tensor 'strided_slice_1:0' shape=(32, ?, 90) dtype=float32>,
    'default_dtype': None,
    'dtype': None,
    'inferred_from': {},
    'input_types': [],
    'inputs': [],
    'key': 'Tlen',
    'keywords': {'batch_dim': 0,
                 'seq_dim': 1,
                 'seq_lengths': <tf.Tensor 'Minimum_1:0' shape=(32,) dtype=int32>},
    'name': 'ReverseSequence',
    'op_type_name': 'ReverseSequence',
    'scope': 'encoder/cell_0/bidirectional_rnn/bw/ReverseSequence/',
    'self': <tensorflow.python.framework.op_def_library.OpDefLibrary object at 0x11a824cf8>,
    'values': <tf.Tensor 'strided_slice_1:0' shape=(32, ?, 90) dtype=float32>}
